// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YarnInstaller
{
    internal sealed partial class Vsix
    {
        public const string Id = "54ec7bf0-19bb-467f-a5a5-15ad0492653b";
        public const string Name = "Yarn Installer";
        public const string Description = @"Makes it easy to restore npm packages using Yarn from within Visual Studio";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "yarn, npm";
    }
}
