// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YarnInstaller
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "62ddb9fa-3968-4ba9-a4c3-bc0b60e819b7";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidAutoloadString = "4b43c563-18aa-4fad-9ace-bc4318727c2c";
        public static Guid guidAutoload = new Guid(guidAutoloadString);

        public const string guidInstallCommandPackageCmdSetString = "7db70b41-a427-475b-8ad1-80415be6eac7";
        public static Guid guidInstallCommandPackageCmdSet = new Guid(guidInstallCommandPackageCmdSetString);

        public const string guidPackageManagementCommandSetString = "b92a417b-195e-41e4-9391-64f7d025020d";
        public static Guid guidPackageManagementCommandSet = new Guid(guidPackageManagementCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int InstallCommandId = 0x0100;
        public const int PackageProviderFileCommandMenuGroup = 0x1022;
    }
}